behaviors:
  MoveToGoal:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 128000
      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.01
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          hidden_units: 128
          num_layers: 2
      curiosity:
        gamma: 0.85
        strength: 0.025
        network_settings:
          hidden_units: 128
          num_layers: 2
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 4250000
    time_horizon: 2048
    summary_freq: 30000
    threaded: true
