behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          hidden_units: 128
          num_layers: 2
      curiosity:
        gamma: 0.85
        strength: 0.025
        network_settings:
          hidden_units: 128
          num_layers: 2
        learning_rate: 0.0003
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 30000
    threaded: true